[build]
	publish = "_site"
	command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "deny"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Strict-Transport-Security = '''
      max-age=31536000;
      includeSubDomains;
      preload
    '''
    Content-Security-Policy = '''
      default-src 'self' https://*.archaeoramblings.com;
      style-src 'self' https://*.archaeoramblings.com 'unsafe-inline';
      img-src 'self' https://*.archaeoramblings.com;
      script-src 'self' https://*.archaeoramblings.com;
      frame-src 'self' https://*.archaeoramblings.com;
	  connect-src 'self' https://*.archaeoramblings.com;
	  base-uri 'self' https://*.archaeoramblings.com;
	  form-action 'self' https://*.archaeoramblings.com
    '''
    Permissions-Policy = '''
      accelerometer=(),
      ambient-light-sensor=(),
      autoplay=(),
      camera=(),
      encrypted-media=(),
      fullscreen=(),
      geolocation=(),
      gyroscope=(),
      magnetometer=(),
      microphone=(),
      midi=(),
      payment=(),
      picture-in-picture=(),
      speaker=(),
      usb=(),
      vibrate=(),
      vr=()
    '''

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # optional, fails build when a category is below a threshold
  [plugins.inputs.thresholds]
    performance = 0.9
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9
    pwa = 0.9

  # optional, deploy the lighthouse report to a path under your site
  [plugins.inputs.audits]
    output_path = "reports/lighthouse.html"