[build]
	publish = "_site"
	command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "deny"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Strict-Transport-Security = '''
      max-age=31536000;
      includeSubDomains;
      preload
    '''
    Content-Security-Policy = '''
      default-src 'self' https://*.archaeoramblings.com;
      style-src 'self' https://*.archaeoramblings.com 'unsafe-inline';
      img-src 'self' https://*.archaeoramblings.com;
      script-src 'self' https://*.archaeoramblings.com 'unsafe-inline';
      frame-src 'self' https://*.archaeoramblings.com;
	  connect-src 'self' https://*.archaeoramblings.com;
	  base-uri 'self' https://*.archaeoramblings.com;
	  form-action 'self' https://*.archaeoramblings.com
    '''
    Permissions-Policy = '''
      accelerometer=(none),
      ambient-light-sensor=(none),
      autoplay=(none),
      camera=(none),
      encrypted-media=(none),
      fullscreen=(none),
      geolocation=(none),
      gyroscope=(none),
      magnetometer=(none),
      microphone=(none),
      midi=(none),
      payment=(none),
      picture-in-picture=(none),
      speaker=(none),
      usb=(none),
      vibrate=(none),
      vr=(none)
    '''